#' Mock data generated by participants in training programme
#'
#' This dataset is purely arbitrary and has no connection to any real-life
#' situation.
#'
#' @format A data frame with 20 'observations' and 5 variables:
#' \describe{
#'    \item{key}{primary key of the dataset}
#'    \item{age}{age, in years, of imaginary subjects}
#'    \item{sex}{gender of imaginary subjects}
#'    \item{height}{height, in m, of the subjects}
#'    \item{weight}{location of the subjects}
#' }
"mockdata"
